package src

func Init() {
	registrasiGuruKelas()
	registrasiGuruPelajaran()
	registrasiMapKepe()
}

/**** registrasi guru kelas ****/
func registrasiGuruKelas() {
	regGuruKelas(ABAH, A2a)
}

/**** registrasi guru pelajaran ****/
func registrasiGuruPelajaran() {
	regGuruPelaj(ABAH, Balaghoh, Mustholah)
	regGuruPelaj(Abd, Ushul)
	regGuruPelaj(Adn, Fiqh)
	regGuruPelaj(Aff, Tauhid)
	regGuruPelaj(Alw, Fiqh)
	regGuruPelaj(Anm, Tauhid)
	regGuruPelaj(Asp, Nahwu, Tauhid)
	regGuruPelaj(Asr, Tajwid)
	regGuruPelaj(Asy, Arab)
	regGuruPelaj(Azz, Nahwu)
	regGuruPelaj(Bch, Tauhid, Akhlaq)
	regGuruPelaj(Bdl, Arab)
	regGuruPelaj(Bgs, Fiqh)
	regGuruPelaj(Dmn, Fiqh)
	regGuruPelaj(Drw, Nahwu)
	regGuruPelaj(Fdl, Imla, Fiqh)
	regGuruPelaj(Fhm, Arab)
	regGuruPelaj(Fqh, Shorof)
	regGuruPelaj(Frh, Arab)
	regGuruPelaj(Frq, Arab)
	regGuruPelaj(Frz, Arab)
	regGuruPelaj(Ft, Nahwu)
	regGuruPelaj(Ftn, Nahwu)
	regGuruPelaj(Gfr, Fiqh)
	regGuruPelaj(Hfd, Shorof, Miftah)
	regGuruPelaj(Hld, Nahwu)
	regGuruPelaj(Hly, Balaghoh)
	regGuruPelaj(Hmd, Tauhid, Shorof)
	regGuruPelaj(Hr, Nahwu, Fiqh)
	regGuruPelaj(Hs, Fiqh)
	regGuruPelaj(Ibr, Shorof, Arab)
	regGuruPelaj(Idm, Akhlaq)
	regGuruPelaj(Ids, Nahwu)
	regGuruPelaj(Idt, Nahwu)
	regGuruPelaj(Irf, Akhlaq)
	regGuruPelaj(Jbr, Nahwu)
	regGuruPelaj(Khl, Akhlaq)
	regGuruPelaj(Lbb, Tajwid)
	regGuruPelaj(Lsn, Tauhid)
	regGuruPelaj(Ltf, Arab)
	regGuruPelaj(Mis, Fiqh, Nahwu)
	regGuruPelaj(Mnj, Akhlaq)
	regGuruPelaj(Mnr, Shorof, Nahwu)
	regGuruPelaj(Mns, Shorof, Fiqh)
	regGuruPelaj(Mrj, Arab)
	regGuruPelaj(Mrw, Fiqh)
	regGuruPelaj(Msh, Imla, Fiqh)
	regGuruPelaj(Msr, Arab)
	regGuruPelaj(Mst, Fiqh)
	regGuruPelaj(Mzn, Ilal)
	regGuruPelaj(Nzr, Nahwu)
	regGuruPelaj(Rf, Nahwu, Ushul, Tasme)
	regGuruPelaj(Rhl, Balaghoh, Arab)
	regGuruPelaj(Rid, Arab)
	regGuruPelaj(Rif, Arab)
	regGuruPelaj(Sbh, Shorof)
	regGuruPelaj(Sdl, Tauhid)
	regGuruPelaj(Sdq, Tauhid)
	regGuruPelaj(Shf, Nahwu, Fiqh)
	regGuruPelaj(Sld, Nahwu)
	regGuruPelaj(Slh, Nahwu)
	regGuruPelaj(Srr, Nahwu)
	regGuruPelaj(St, Arab)
	regGuruPelaj(Uhn, Arab)
	regGuruPelaj(Uhs, Fiqh)
	regGuruPelaj(Ul, Tauhid)
	regGuruPelaj(Umm, Tauhid)
	regGuruPelaj(Umr, Akhlaq)
	regGuruPelaj(Urb, Shorof)
	regGuruPelaj(Usm, Nahwu)
	regGuruPelaj(Usy, Tauhid, Arab)
	regGuruPelaj(Utj, Nahwu, Tasme)
	regGuruPelaj(Wf, Shorof)
	regGuruPelaj(Whb, Tajwid)
	regGuruPelaj(Ydn, Akhlaq)
	regGuruPelaj(Yhy, Arab)
}

/**** mapping pelajaran kelas ****/
func registrasiMapKepe() {
	// Nzr.mapKepe(T1a.Kode, Nahwu.Kode)
}
